wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"

urlpatterns = [
    path('', views.index_view, name="index"),
    path('add/', views.add_view, name="add"),
    path('search/', views.search_view, name="search"),
    path('edit/',views.edit_view, name="edit"),
    path('<str:name>/', views.page_view, name="page"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from django import forms

class WikiForm(forms.Form):
    title = forms.CharField(label="title", max_length="100", strip="True")
    content = forms.CharField(
                widget=forms.Textarea(
                    attrs={
                            'placeholder':"Enter content in markdown"
                        }
                )  
            )

wiki/encyclopedia/views.py
import random
import markdown2

from django.shortcuts import render

from . import util
from .forms import WikiForm

from django.http import HttpResponseRedirect
from django.urls import reverse



def index_view(request):
    #print("index_view")
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def add_view(request):
    #print("add_view")
    form = WikiForm()
    if request.method == "POST":

        form = WikiForm(request.POST)
        

        if form.is_valid():    
            upper_list = [x.upper() for x in util.list_entries()]   
            title = form.cleaned_data["title"]
            
            #print("form is valid")

            #save if title does not exist
            if not title.upper() in upper_list:
                content = form.cleaned_data["content"]
                util.save_entry(title,(content.encode('ascii')))
                #print("saved")
                return HttpResponseRedirect(f"http://127.0.0.1:8000/wiki/{title}") 
                
            #title already exists 
            else:
                #print("Name not available")
                return render(request,"encyclopedia/error.html",{

                    "message": f"Sorry {title.upper()} Already Exists In Directory",
                })
            
        else:        
            return render(request,"encyclopedia/error.html",{
                    "message": "Invalid Form Submission"
                })

    return render(request, "encyclopedia/add.html",{
                "form": form,
            })

def page_view(request,name):
    #print("page_view")
    can_edit = False

    if name == "random":
        can_edit = True
        random_page = random.choice(util.list_entries())
        page = markdown2.markdown(util.get_entry(random_page))
        name = random_page

    elif util.get_entry(name) == None :
        return render(request,"encyclopedia/error.html",{
                    "message": f"Sorry {name.upper()} Doest Not Exist"
                })

    else:
        can_edit = True
        page = markdown2.markdown(util.get_entry(name))

    return render(request,"encyclopedia/search.html",{
            "page": page,
            "initial_search": name,
            "can_edit": can_edit,
        })


def search_view(request):
    
    can_edit = False

    if 'q' in request.GET :
        print(request.GET['q'])
    
        upper_list = [x.upper() for x in util.list_entries()]

        if request.GET['q'].upper() in upper_list : 

            can_edit = True

            return render(request,"encyclopedia/search.html",{
                "page": markdown2.markdown(util.get_entry(request.GET['q'])),
                "initial_search": request.GET['q'],
                "can_edit": can_edit,
            })


        else:
            available = []
            for wiki in util.list_entries():
                if wiki.startswith(request.GET['q'].upper()):
                    available.append(wiki)

            if not available:        
                return render(request,"encyclopedia/error.html",{
                    "message": f"Sorry {request.GET['q'].upper()} Doest Not Exist",
                })

            else:
                return render(request,"encyclopedia/search.html",{

                    "wikis": available,
                    "initial_search": request.GET['q'],
                    "can_edit": can_edit,
                })
    else:
        return HttpResponseRedirect(reverse("encyclopedia:index"))


def edit_view(request):
    if request.method == 'GET':
        title = request.GET["old_content"]
        current_page = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            'title':title,
            'content':current_page,
        })

    if request.method == 'POST':
        form = WikiForm(request.POST)

        if form.is_valid():   
            #print("form is valid") 
            
            title = form.cleaned_data["title"] 
            content = form.cleaned_data["content"]

            util.save_entry(title,(content.encode('ascii')))
            return HttpResponseRedirect(f"http://127.0.0.1:8000/wiki/{title}")
        
        else:
            #print("not valid")
            return render(request,"encyclopedia/error.html",{
                    "message": "Invalid Form Submission"
                })

        
        

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add Page
{% endblock %}

{% block body%}
    <div class="division">
        <form action="{% url 'encyclopedia:add' %}" method="POST">
            {% csrf_token %} 

            <!--
            {{form.as_p}}
                <input name="title" style="strip:True" required>
                <Textarea name="content" placeholder="Enter content in markdown" required></Textarea>
            -->
            <div>
                <h3>Title:</h3>
                {{form.title}}
            </div>

            <div>
                <h3>Content:</h3>
                {{form.content}}

            </div> 


            <input type="submit" value="SAVE">

        </form>
    <div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{title}}
{% endblock %}

{% block body %}
    <div class="division">
        <form action="{% url 'encyclopedia:edit' %}"  method="POST">   
            {% csrf_token %}
            <div>
                <h3>Title:</h3>
                <input value="{{title}}" name="title" style="strip:True" autocomplete="off" required>
            </div>

            <div>
                <h3>Content:</h3>

                <Textarea name="content" placeholder="Enter content in markdown" required>{{content}}</Textarea>
            </div>

            <div>
                <input type="submit" value="SAVE CHANGES">
            </div>

        </form>   
    </div> 

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block  body%}
    <h1 style="text-align:center" class="division"> {{message}} </h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="division">
        <h1>All Pages</h1>
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:page' name=entry %}" > {{ entry }} </a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body style="width:99%%">
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>

                </div>
                <div>
                    <a href="{% url 'encyclopedia:page' name="random" %}">Random Page</a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>

            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{initial_search}}
{% endblock %}

{% block  body%}
    <div class="division">
        <div>{{ page|safe }}</div>

        {% if can_edit %}
            <form action={% url 'encyclopedia:edit' %} method ="GET">
                <input value="{{initial_search}}" type="text" name="old_content" hidden="True" readonly>
                <input type="submit" value="EDIT">

            </form>  
        {% endif %} 

        <ul style="margin-top:50px">        
            {% for wiki in wikis %}
                <li style="margin-bottom:20px"><a href="{% url 'encyclopedia:page' name=wiki %}" > {{ wiki }} </a></li>
            {% endfor %}

        </ul>
    </div>
{% endblock %}